### ISSUE TITLE
"We cannot get Airport info from website..." error

### ISSUE THREAD

**Issue by yashris** [stylerx/OpenACARS#2]
Hello, I am new to OpenAcars and use the latest release version of OPenacars. When I click on Start FLight button, I get the error, "We cannot get Airport info from website..." Please can anyone resolve this?
Thanks

**Comment by stylerx** [comment]
You have the [PHPVMS Module](https://github.com/stylerx/OpenACARS-phpvms-module) correctly installed in your VA website? If it is correctly installed, please inform your VA website URL.

**Comment by yashris** [comment]
Hey, thanks for the reply and yeah I have installed the module correctly.My VA website link is http://user.indiava.in/

Thanks

**Comment by stylerx** [comment]
Please send your `DebugLog.log` file (this file is located at `%localappdata%\OpenACARS`), so that I can start fixing the error.

**Comment by yashris** [comment]
Hey, here is the debuglog.log file. Please fix it ASAP..Thanks

**Comment by stylerx** [comment]
Download again the  [PHPVMS Module](https://github.com/stylerx/OpenACARS-phpvms-module) and replace the old version if it. Tell me if this fix the issue.

**Comment by yashris** [comment]
Yeah it worked, thanks a lot
